name: '@upupming/zhr-action'
description: '浙江大学健康打卡脚本'
inputs:
  username:
    description: '浙大通行证用户名'
    required: true
  password:
    description: '浙大通行证密码'
    required: false
  cookie_eai_sess:
    description: '健康上报网页 eai-sess Cookie'
    required: false
  dingtalk_token:
    description: '钉钉机器人通知 access_token'
    required: false
runs:
  using: 'node16'
  main: 'dist/action.js'
